# General Settings
name: Edwin Knuth
job_title: Software engineer
email: eknuth@gmail.com
description: front end applications and operations, reusable components, data visualization, full stack
avatar: http://www.gravatar.com/avatar/9e27ba264dccbe5149fd08b17f5bdeb1?s=140
favicon: /favicon.ico
twitter_handler: eknuth
analytics_code: UA-XXXXXXX-2
disqus: iknuth

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/eknuth' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'eknuth' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_mood: 1
show_email: 1
show_rss: 1
show_comments: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Outputting
#permalink: /:categories/:title.html
category_dir: categories

# Plugins
gems: [jekyll-paginate, jekyll-gist]


# Pagination
paginate: 3
paginate_path: "/page:num/"

# Conversion
markdown: kramdown

# Post Settings
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
